name: home_indicator_example
description: Demonstrates how to use the home_indicator plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  home_indicator:
    path: ../

flutter:
  uses-material-design: true
